import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import { detectTools, generateQualityScript, installHooks } from '../src/hooks';
import type { DetectedTool } from '../src/types';

describe('detectTools', () => {
  const tempDir = path.join(__dirname, 'fixtures', 'temp-hooks-test');

  beforeEach(() => {
    fs.mkdirSync(tempDir, { recursive: true });
  });

  afterEach(() => {
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  it('应检测 package.json 中的 typescript', () => {
    fs.writeFileSync(path.join(tempDir, 'package.json'), JSON.stringify({
      devDependencies: { typescript: '^5.0.0' }
    }));
    const tools = detectTools(tempDir);
    const ts = tools.find(t => t.name === 'typescript');
    expect(ts?.detected).toBe(true);
    expect(ts?.source).toContain('devDependencies');
    expect(ts?.level).toBe('block');
  });

  it('应检测 tsconfig.json 文件', () => {
    fs.writeFileSync(path.join(tempDir, 'package.json'), JSON.stringify({}));
    fs.writeFileSync(path.join(tempDir, 'tsconfig.json'), '{}');
    const tools = detectTools(tempDir);
    const ts = tools.find(t => t.name === 'typescript');
    expect(ts?.detected).toBe(true);
    expect(ts?.source).toContain('tsconfig.json');
  });

  it('应检测 eslint（依赖方式）', () => {
    fs.writeFileSync(path.join(tempDir, 'package.json'), JSON.stringify({
      devDependencies: { eslint: '^8.0.0' }
    }));
    const tools = detectTools(tempDir);
    const eslint = tools.find(t => t.name === 'eslint');
    expect(eslint?.detected).toBe(true);
    expect(eslint?.level).toBe('warn');
  });

  it('应检测 eslint.config.js 文件', () => {
    fs.writeFileSync(path.join(tempDir, 'package.json'), JSON.stringify({}));
    fs.writeFileSync(path.join(tempDir, 'eslint.config.js'), '');
    const tools = detectTools(tempDir);
    const eslint = tools.find(t => t.name === 'eslint');
    expect(eslint?.detected).toBe(true);
    expect(eslint?.source).toContain('eslint.config.js');
  });

  it('应检测 biome', () => {
    fs.writeFileSync(path.join(tempDir, 'package.json'), JSON.stringify({
      devDependencies: { '@biomejs/biome': '^1.0.0' }
    }));
    const tools = detectTools(tempDir);
    const biome = tools.find(t => t.name === 'biome');
    expect(biome?.detected).toBe(true);
    expect(biome?.level).toBe('warn');
  });

  it('应检测 prettier', () => {
    fs.writeFileSync(path.join(tempDir, 'package.json'), JSON.stringify({
      dependencies: { prettier: '^3.0.0' }
    }));
    const tools = detectTools(tempDir);
    const prettier = tools.find(t => t.name === 'prettier');
    expect(prettier?.detected).toBe(true);
    expect(prettier?.level).toBe('warn');
  });

  it('应检测 vitest', () => {
    fs.writeFileSync(path.join(tempDir, 'package.json'), JSON.stringify({
      devDependencies: { vitest: '^1.0.0' }
    }));
    const tools = detectTools(tempDir);
    const vitest = tools.find(t => t.name === 'vitest');
    expect(vitest?.detected).toBe(true);
    expect(vitest?.level).toBe('block');
  });

  it('应检测 jest（配置文件方式）', () => {
    fs.writeFileSync(path.join(tempDir, 'package.json'), JSON.stringify({}));
    fs.writeFileSync(path.join(tempDir, 'jest.config.js'), '');
    const tools = detectTools(tempDir);
    const jest = tools.find(t => t.name === 'jest');
    expect(jest?.detected).toBe(true);
  });

  it('无工具时全部 detected 为 false', () => {
    fs.writeFileSync(path.join(tempDir, 'package.json'), JSON.stringify({}));
    const tools = detectTools(tempDir);
    expect(tools.every(t => !t.detected)).toBe(true);
  });

  it('无 package.json 时不崩溃', () => {
    const tools = detectTools(tempDir);
    expect(tools.every(t => !t.detected)).toBe(true);
  });
});

describe('generateQualityScript', () => {
  it('始终包含变更检测和 fnmap 更新', () => {
    const script = generateQualityScript([]);
    expect(script).toContain('git diff');
    expect(script).toContain('fnmap --changed');
    expect(script).toContain('Auto-generated by fnmap --hooks');
  });

  it('检测到 typescript 时包含 tsc 检查（block 级别）', () => {
    const tools: DetectedTool[] = [
      { name: 'typescript', detected: true, source: 'devDependencies', level: 'block' }
    ];
    const script = generateQualityScript(tools);
    expect(script).toContain('tsc --noEmit');
    expect(script).toContain('BLOCK_ERRORS');
  });

  it('检测到 eslint 时包含 eslint 检查（warn 级别）', () => {
    const tools: DetectedTool[] = [
      { name: 'eslint', detected: true, source: 'devDependencies', level: 'warn' }
    ];
    const script = generateQualityScript(tools);
    expect(script).toContain('eslint');
    expect(script).toContain('WARN_MESSAGES');
  });

  it('检测到 biome 时包含 biome 检查', () => {
    const tools: DetectedTool[] = [
      { name: 'biome', detected: true, source: 'devDependencies', level: 'warn' }
    ];
    const script = generateQualityScript(tools);
    expect(script).toContain('biome check');
  });

  it('检测到 prettier 时包含 prettier 检查', () => {
    const tools: DetectedTool[] = [
      { name: 'prettier', detected: true, source: 'devDependencies', level: 'warn' }
    ];
    const script = generateQualityScript(tools);
    expect(script).toContain('prettier --check');
  });

  it('检测到 vitest 时包含测试运行（block 级别）', () => {
    const tools: DetectedTool[] = [
      { name: 'vitest', detected: true, source: 'devDependencies', level: 'block' }
    ];
    const script = generateQualityScript(tools);
    expect(script).toContain('vitest run');
    expect(script).toContain('BLOCK_ERRORS');
  });

  it('检测到 jest 时包含 jest 运行', () => {
    const tools: DetectedTool[] = [
      { name: 'jest', detected: true, source: 'devDependencies', level: 'block' }
    ];
    const script = generateQualityScript(tools);
    expect(script).toContain('npx jest');
  });

  it('检测到 mocha 时包含 mocha 运行', () => {
    const tools: DetectedTool[] = [
      { name: 'mocha', detected: true, source: 'devDependencies', level: 'block' }
    ];
    const script = generateQualityScript(tools);
    expect(script).toContain('npx mocha');
  });

  it('未检测到的工具不包含在脚本中', () => {
    const tools: DetectedTool[] = [
      { name: 'eslint', detected: false, source: '', level: 'warn' }
    ];
    const script = generateQualityScript(tools);
    expect(script).not.toContain('eslint');
  });

  it('多个工具组合生成', () => {
    const tools: DetectedTool[] = [
      { name: 'typescript', detected: true, source: 'devDependencies', level: 'block' },
      { name: 'prettier', detected: true, source: 'devDependencies', level: 'warn' },
      { name: 'vitest', detected: true, source: 'devDependencies', level: 'block' },
    ];
    const script = generateQualityScript(tools);
    expect(script).toContain('tsc --noEmit');
    expect(script).toContain('prettier --check');
    expect(script).toContain('vitest run');
  });
});

describe('installHooks', () => {
  const tempDir = path.join(__dirname, 'fixtures', 'temp-hooks-install');

  beforeEach(() => {
    fs.mkdirSync(tempDir, { recursive: true });
  });

  afterEach(() => {
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  it('应创建 .claude/settings.json 和 hooks 脚本', () => {
    const tools: DetectedTool[] = [
      { name: 'typescript', detected: true, source: 'devDependencies', level: 'block' }
    ];
    installHooks(tempDir, tools);
    expect(fs.existsSync(path.join(tempDir, '.claude', 'settings.json'))).toBe(true);
    expect(fs.existsSync(path.join(tempDir, '.claude', 'hooks', 'quality-check.sh'))).toBe(true);
  });

  it('settings.json 应包含 PreToolUse 和 Stop hooks', () => {
    const tools: DetectedTool[] = [
      { name: 'typescript', detected: true, source: 'devDependencies', level: 'block' }
    ];
    installHooks(tempDir, tools);
    const settings = JSON.parse(fs.readFileSync(path.join(tempDir, '.claude', 'settings.json'), 'utf-8'));
    expect(settings.hooks.PreToolUse).toBeDefined();
    expect(settings.hooks.Stop).toBeDefined();
    expect(settings.hooks.PreToolUse[0].matcher).toBe('Edit|Write');
    expect(settings.hooks.Stop[0].hooks[0].command).toContain('quality-check.sh');
  });

  it('应合并已有的 settings.json 而非覆盖', () => {
    fs.mkdirSync(path.join(tempDir, '.claude'), { recursive: true });
    fs.writeFileSync(path.join(tempDir, '.claude', 'settings.json'), JSON.stringify({
      permissions: { allow: ['Bash(git:*)'] },
      hooks: {
        SessionStart: [{ matcher: '', hooks: [{ type: 'command', command: 'echo hi' }] }]
      }
    }, null, 2));

    installHooks(tempDir, []);

    const settings = JSON.parse(fs.readFileSync(path.join(tempDir, '.claude', 'settings.json'), 'utf-8'));
    expect(settings.permissions.allow).toContain('Bash(git:*)');
    expect(settings.hooks.SessionStart).toBeDefined();
    expect(settings.hooks.PreToolUse).toBeDefined();
    expect(settings.hooks.Stop).toBeDefined();
  });

  it('幂等：重复安装应更新而非重复添加', () => {
    installHooks(tempDir, []);
    installHooks(tempDir, []);

    const settings = JSON.parse(fs.readFileSync(path.join(tempDir, '.claude', 'settings.json'), 'utf-8'));
    const fnmapPreHooks = settings.hooks.PreToolUse.filter(
      (h: any) => h.hooks?.some((hh: any) => hh.statusMessage?.includes('fnmap'))
    );
    expect(fnmapPreHooks.length).toBe(1);

    const fnmapStopHooks = settings.hooks.Stop.filter(
      (h: any) => h.hooks?.some((hh: any) => hh.command?.includes('quality-check.sh'))
    );
    expect(fnmapStopHooks.length).toBe(1);
  });

  it('quality-check.sh 应包含检测到的工具', () => {
    const tools: DetectedTool[] = [
      { name: 'vitest', detected: true, source: 'devDependencies', level: 'block' }
    ];
    installHooks(tempDir, tools);
    const script = fs.readFileSync(path.join(tempDir, '.claude', 'hooks', 'quality-check.sh'), 'utf-8');
    expect(script).toContain('#!/bin/bash');
    expect(script).toContain('vitest run');
  });
});
