#!/bin/bash
# Auto-generated by fnmap --hooks
# 自动代码质量检查脚本 - 由 fnmap 生成，勿手动编辑

cd "${CLAUDE_PROJECT_DIR:-.}" || exit 0

# 检测变更的 JS/TS/Vue 文件
CHANGED=$(git diff --name-only --diff-filter=ACMR HEAD 2>/dev/null | grep -E '\.(js|ts|jsx|tsx|vue)$')
UNTRACKED=$(git ls-files --others --exclude-standard 2>/dev/null | grep -E '\.(js|ts|jsx|tsx|vue)$')
ALL_CHANGED=$(printf '%s\n%s' "$CHANGED" "$UNTRACKED" | sort -u | grep -v '^$')

[ -z "$ALL_CHANGED" ] && exit 0

BLOCK_ERRORS=""
WARN_MESSAGES=""

# fnmap 索引更新
fnmap --changed 2>/dev/null || true

# TypeScript 类型检查
TS_OUTPUT=$(npx tsc --noEmit 2>&1)
if [ $? -ne 0 ]; then
  TS_ERRORS=$(echo "$TS_OUTPUT" | head -30)
  BLOCK_ERRORS="$BLOCK_ERRORS\n[TypeScript 类型错误]\n$TS_ERRORS"
fi

# Prettier 格式检查（仅变更文件）
PRETTIER_OUTPUT=$(echo "$ALL_CHANGED" | xargs npx prettier --check 2>&1)
if [ $? -ne 0 ]; then
  PRETTIER_ERRORS=$(echo "$PRETTIER_OUTPUT" | grep -v '^\[warn\]' | head -20)
  WARN_MESSAGES="$WARN_MESSAGES\n[Prettier 格式问题]\n$PRETTIER_ERRORS"
fi

# Vitest 测试
TEST_OUTPUT=$(npx vitest run 2>&1)
if [ $? -ne 0 ]; then
  TEST_ERRORS=$(echo "$TEST_OUTPUT" | tail -30)
  BLOCK_ERRORS="$BLOCK_ERRORS\n[测试失败]\n$TEST_ERRORS"
fi

# 转义 JSON 并输出结果
escape_json() {
  node -e "let d='';process.stdin.on('data',c=>d+=c);process.stdin.on('end',()=>console.log(JSON.stringify(d)));"
}

if [ -n "$BLOCK_ERRORS" ]; then
  ESCAPED=$(echo -e "$BLOCK_ERRORS" | escape_json)
  echo "{\"decision\":\"block\",\"reason\":$ESCAPED}"
elif [ -n "$WARN_MESSAGES" ]; then
  ESCAPED=$(echo -e "$WARN_MESSAGES" | escape_json)
  echo "{\"systemMessage\":$ESCAPED}"
fi
