import fs from 'fs';
import path from 'path';
import type { DetectedTool } from '../types';

/** 读取 package.json 的所有依赖名 */
function readDeps(projectDir: string): Set<string> {
  const pkgPath = path.join(projectDir, 'package.json');
  if (!fs.existsSync(pkgPath)) return new Set();
  try {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
    return new Set([
      ...Object.keys(pkg.dependencies || {}),
      ...Object.keys(pkg.devDependencies || {})
    ]);
  } catch {
    return new Set();
  }
}

/** 检查配置文件是否存在，返回匹配的文件名 */
function findConfigFile(projectDir: string, patterns: string[]): string | null {
  for (const pattern of patterns) {
    if (pattern.endsWith('*')) {
      const prefix = pattern.slice(0, -1);
      try {
        const entries = fs.readdirSync(projectDir).filter(f => f.startsWith(prefix));
        if (entries.length > 0) return entries[0] ?? null;
      } catch { /* ignore */ }
    } else {
      if (fs.existsSync(path.join(projectDir, pattern))) return pattern;
    }
  }
  return null;
}

/** 判断依赖来源描述 */
function depSource(projectDir: string, depName: string): string {
  const pkgPath = path.join(projectDir, 'package.json');
  if (!fs.existsSync(pkgPath)) return '';
  try {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
    if (pkg.devDependencies?.[depName]) return 'devDependencies';
    if (pkg.dependencies?.[depName]) return 'dependencies';
  } catch { /* ignore */ }
  return '';
}

/** 工具检测规则定义 */
interface ToolRule {
  name: string;
  depNames: string[];
  configPatterns: string[];
  level: 'block' | 'warn';
}

/** 支持检测的工具规则列表 */
const TOOL_RULES: ToolRule[] = [
  { name: 'typescript', depNames: ['typescript'], configPatterns: ['tsconfig.json'], level: 'block' },
  { name: 'eslint', depNames: ['eslint'], configPatterns: ['.eslintrc*', 'eslint.config.*'], level: 'warn' },
  { name: 'biome', depNames: ['@biomejs/biome'], configPatterns: ['biome.json', 'biome.jsonc'], level: 'warn' },
  { name: 'prettier', depNames: ['prettier'], configPatterns: ['.prettierrc*', 'prettier.config.*'], level: 'warn' },
  { name: 'vitest', depNames: ['vitest'], configPatterns: [], level: 'block' },
  { name: 'jest', depNames: ['jest'], configPatterns: ['jest.config.*'], level: 'block' },
  { name: 'mocha', depNames: ['mocha'], configPatterns: ['.mocharc*'], level: 'block' },
];

// 各工具的检查脚本片段
const TOOL_SCRIPTS: Record<string, string> = {
  typescript: `# TypeScript 类型检查
TS_OUTPUT=$(npx tsc --noEmit 2>&1)
if [ $? -ne 0 ]; then
  TS_ERRORS=$(echo "$TS_OUTPUT" | head -30)
  BLOCK_ERRORS="$BLOCK_ERRORS\\n[TypeScript 类型错误]\\n$TS_ERRORS"
fi`,
  eslint: `# ESLint 检查（仅变更文件）
LINT_OUTPUT=$(echo "$ALL_CHANGED" | xargs npx eslint --no-warn 2>&1)
if [ $? -ne 0 ]; then
  LINT_ERRORS=$(echo "$LINT_OUTPUT" | head -30)
  WARN_MESSAGES="$WARN_MESSAGES\\n[ESLint 问题]\\n$LINT_ERRORS"
fi`,
  biome: `# Biome 检查（仅变更文件）
BIOME_OUTPUT=$(echo "$ALL_CHANGED" | xargs npx biome check 2>&1)
if [ $? -ne 0 ]; then
  BIOME_ERRORS=$(echo "$BIOME_OUTPUT" | head -30)
  WARN_MESSAGES="$WARN_MESSAGES\\n[Biome 问题]\\n$BIOME_ERRORS"
fi`,
  prettier: `# Prettier 格式检查（仅变更文件）
PRETTIER_OUTPUT=$(echo "$ALL_CHANGED" | xargs npx prettier --check 2>&1)
if [ $? -ne 0 ]; then
  PRETTIER_ERRORS=$(echo "$PRETTIER_OUTPUT" | grep -v '^\\[warn\\]' | head -20)
  WARN_MESSAGES="$WARN_MESSAGES\\n[Prettier 格式问题]\\n$PRETTIER_ERRORS"
fi`,
  vitest: `# Vitest 测试
TEST_OUTPUT=$(npx vitest run 2>&1)
if [ $? -ne 0 ]; then
  TEST_ERRORS=$(echo "$TEST_OUTPUT" | tail -30)
  BLOCK_ERRORS="$BLOCK_ERRORS\\n[测试失败]\\n$TEST_ERRORS"
fi`,
  jest: `# Jest 测试
TEST_OUTPUT=$(npx jest 2>&1)
if [ $? -ne 0 ]; then
  TEST_ERRORS=$(echo "$TEST_OUTPUT" | tail -30)
  BLOCK_ERRORS="$BLOCK_ERRORS\\n[测试失败]\\n$TEST_ERRORS"
fi`,
  mocha: `# Mocha 测试
TEST_OUTPUT=$(npx mocha 2>&1)
if [ $? -ne 0 ]; then
  TEST_ERRORS=$(echo "$TEST_OUTPUT" | tail -30)
  BLOCK_ERRORS="$BLOCK_ERRORS\\n[测试失败]\\n$TEST_ERRORS"
fi`
};

/** 根据检测到的工具生成质量检查脚本 */
export function generateQualityScript(detectedTools: DetectedTool[]): string {
  const enabledTools = detectedTools.filter(t => t.detected);

  const toolSections = enabledTools
    .map(t => TOOL_SCRIPTS[t.name])
    .filter(Boolean)
    .join('\n\n');

  return `#!/bin/bash
# Auto-generated by fnmap --hooks
# 自动代码质量检查脚本 - 由 fnmap 生成，勿手动编辑

cd "\${CLAUDE_PROJECT_DIR:-.}" || exit 0

# 检测变更的 JS/TS/Vue 文件
CHANGED=$(git diff --name-only --diff-filter=ACMR HEAD 2>/dev/null | grep -E '\\.(js|ts|jsx|tsx|vue)$')
UNTRACKED=$(git ls-files --others --exclude-standard 2>/dev/null | grep -E '\\.(js|ts|jsx|tsx|vue)$')
ALL_CHANGED=$(printf '%s\\n%s' "$CHANGED" "$UNTRACKED" | sort -u | grep -v '^$')

[ -z "$ALL_CHANGED" ] && exit 0

BLOCK_ERRORS=""
WARN_MESSAGES=""

# fnmap 索引更新
fnmap --changed 2>/dev/null || true

${toolSections}

# 转义 JSON 并输出结果
escape_json() {
  node -e "let d='';process.stdin.on('data',c=>d+=c);process.stdin.on('end',()=>console.log(JSON.stringify(d)));"
}

if [ -n "$BLOCK_ERRORS" ]; then
  ESCAPED=$(echo -e "$BLOCK_ERRORS" | escape_json)
  echo "{\\"decision\\":\\"block\\",\\"reason\\":$ESCAPED}"
elif [ -n "$WARN_MESSAGES" ]; then
  ESCAPED=$(echo -e "$WARN_MESSAGES" | escape_json)
  echo "{\\"systemMessage\\":$ESCAPED}"
fi
`;
}

/** 检测项目中安装的工具 */
export function detectTools(projectDir: string): DetectedTool[] {
  const deps = readDeps(projectDir);

  return TOOL_RULES.map(rule => {
    const foundDep = rule.depNames.find(d => deps.has(d));
    if (foundDep) {
      const src = depSource(projectDir, foundDep);
      return { name: rule.name, detected: true, source: src || 'dependencies', level: rule.level };
    }
    const configFile = findConfigFile(projectDir, rule.configPatterns);
    if (configFile) {
      return { name: rule.name, detected: true, source: configFile, level: rule.level };
    }
    return { name: rule.name, detected: false, source: '', level: rule.level };
  });
}
