import fs from 'fs';
import path from 'path';
import * as readline from 'node:readline';
import type { DetectedTool } from '../types';
import { COLORS } from '../constants';

/** 读取并解析 package.json */
function readPkg(projectDir: string): Record<string, any> | null {
  const pkgPath = path.join(projectDir, 'package.json');
  if (!fs.existsSync(pkgPath)) return null;
  try {
    return JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
  } catch {
    return null;
  }
}

/** 从 package.json 提取所有依赖名 */
function getDeps(pkg: Record<string, any> | null): Set<string> {
  if (!pkg) return new Set();
  return new Set([
    ...Object.keys(pkg.dependencies || {}),
    ...Object.keys(pkg.devDependencies || {})
  ]);
}

/** 检查配置文件是否存在，返回匹配的文件名 */
function findConfigFile(projectDir: string, patterns: string[]): string | null {
  for (const pattern of patterns) {
    if (pattern.endsWith('*')) {
      const prefix = pattern.slice(0, -1);
      try {
        const entries = fs.readdirSync(projectDir).filter(f => f.startsWith(prefix));
        if (entries.length > 0) return entries[0] ?? null;
      } catch { /* ignore */ }
    } else {
      if (fs.existsSync(path.join(projectDir, pattern))) return pattern;
    }
  }
  return null;
}

/** 判断依赖来源描述 */
function depSource(pkg: Record<string, any> | null, depName: string): string {
  if (!pkg) return '';
  if (pkg.devDependencies?.[depName]) return 'devDependencies';
  if (pkg.dependencies?.[depName]) return 'dependencies';
  return '';
}

/** 工具检测规则定义 */
interface ToolRule {
  name: string;
  depNames: string[];
  configPatterns: string[];
  level: 'block' | 'warn';
}

/** 支持检测的工具规则列表 */
const TOOL_RULES: ToolRule[] = [
  { name: 'typescript', depNames: ['typescript'], configPatterns: ['tsconfig.json'], level: 'block' },
  { name: 'eslint', depNames: ['eslint'], configPatterns: ['.eslintrc*', 'eslint.config.*'], level: 'warn' },
  { name: 'biome', depNames: ['@biomejs/biome'], configPatterns: ['biome.json', 'biome.jsonc'], level: 'warn' },
  { name: 'prettier', depNames: ['prettier'], configPatterns: ['.prettierrc*', 'prettier.config.*'], level: 'warn' },
  { name: 'vitest', depNames: ['vitest'], configPatterns: [], level: 'block' },
  { name: 'jest', depNames: ['jest'], configPatterns: ['jest.config.*'], level: 'block' },
  { name: 'mocha', depNames: ['mocha'], configPatterns: ['.mocharc*'], level: 'block' },
];

// 各工具的检查脚本片段
const TOOL_SCRIPTS: Record<string, string> = {
  typescript: `# TypeScript 类型检查
TS_OUTPUT=$(npx tsc --noEmit 2>&1)
if [ $? -ne 0 ]; then
  TS_ERRORS=$(echo "$TS_OUTPUT" | head -30)
  BLOCK_ERRORS="$BLOCK_ERRORS\\n[TypeScript 类型错误]\\n$TS_ERRORS"
fi`,
  eslint: `# ESLint 检查（仅变更文件）
LINT_OUTPUT=$(echo "$ALL_CHANGED" | xargs -d '\\n' npx eslint --no-warn 2>&1)
if [ $? -ne 0 ]; then
  LINT_ERRORS=$(echo "$LINT_OUTPUT" | head -30)
  WARN_MESSAGES="$WARN_MESSAGES\\n[ESLint 问题]\\n$LINT_ERRORS"
fi`,
  biome: `# Biome 检查（仅变更文件）
BIOME_OUTPUT=$(echo "$ALL_CHANGED" | xargs -d '\\n' npx biome check 2>&1)
if [ $? -ne 0 ]; then
  BIOME_ERRORS=$(echo "$BIOME_OUTPUT" | head -30)
  WARN_MESSAGES="$WARN_MESSAGES\\n[Biome 问题]\\n$BIOME_ERRORS"
fi`,
  prettier: `# Prettier 格式检查（仅变更文件）
PRETTIER_OUTPUT=$(echo "$ALL_CHANGED" | xargs -d '\\n' npx prettier --check 2>&1)
if [ $? -ne 0 ]; then
  PRETTIER_ERRORS=$(echo "$PRETTIER_OUTPUT" | grep -v '^\\[warn\\]' | head -20)
  WARN_MESSAGES="$WARN_MESSAGES\\n[Prettier 格式问题]\\n$PRETTIER_ERRORS"
fi`,
  vitest: `# Vitest 测试
TEST_OUTPUT=$(npx vitest run 2>&1)
if [ $? -ne 0 ]; then
  TEST_ERRORS=$(echo "$TEST_OUTPUT" | tail -30)
  BLOCK_ERRORS="$BLOCK_ERRORS\\n[测试失败]\\n$TEST_ERRORS"
fi`,
  jest: `# Jest 测试
TEST_OUTPUT=$(npx jest 2>&1)
if [ $? -ne 0 ]; then
  TEST_ERRORS=$(echo "$TEST_OUTPUT" | tail -30)
  BLOCK_ERRORS="$BLOCK_ERRORS\\n[测试失败]\\n$TEST_ERRORS"
fi`,
  mocha: `# Mocha 测试
TEST_OUTPUT=$(npx mocha 2>&1)
if [ $? -ne 0 ]; then
  TEST_ERRORS=$(echo "$TEST_OUTPUT" | tail -30)
  BLOCK_ERRORS="$BLOCK_ERRORS\\n[测试失败]\\n$TEST_ERRORS"
fi`
};

/** 根据检测到的工具生成质量检查脚本 */
export function generateQualityScript(detectedTools: DetectedTool[]): string {
  const enabledTools = detectedTools.filter(t => t.detected);

  const toolSections = enabledTools
    .map(t => TOOL_SCRIPTS[t.name])
    .filter(Boolean)
    .join('\n\n');

  return `#!/bin/bash
# Auto-generated by fnmap --hooks
# 自动代码质量检查脚本 - 由 fnmap 生成，勿手动编辑

cd "\${CLAUDE_PROJECT_DIR:-.}" || exit 0

# 检测变更的 JS/TS/Vue 文件
CHANGED=$(git diff --name-only --diff-filter=ACMR HEAD 2>/dev/null | grep -E '\\.(js|ts|jsx|tsx|vue)$')
UNTRACKED=$(git ls-files --others --exclude-standard 2>/dev/null | grep -E '\\.(js|ts|jsx|tsx|vue)$')
ALL_CHANGED=$(printf '%s\\n%s' "$CHANGED" "$UNTRACKED" | sort -u | grep -v '^$')

[ -z "$ALL_CHANGED" ] && exit 0

BLOCK_ERRORS=""
WARN_MESSAGES=""

# fnmap 索引更新
fnmap --changed 2>/dev/null || true

${toolSections}

# 转义 JSON 并输出结果
escape_json() {
  node -e "let d='';process.stdin.on('data',c=>d+=c);process.stdin.on('end',()=>console.log(JSON.stringify(d)));"
}

if [ -n "$BLOCK_ERRORS" ]; then
  ESCAPED=$(echo -e "$BLOCK_ERRORS" | escape_json)
  echo "{\\"decision\\":\\"block\\",\\"reason\\":$ESCAPED}"
elif [ -n "$WARN_MESSAGES" ]; then
  ESCAPED=$(echo -e "$WARN_MESSAGES" | escape_json)
  echo "{\\"systemMessage\\":$ESCAPED}"
fi
`;
}

// fnmap hooks 的固定标识，用于幂等更新
const FNMAP_PRE_HOOK_MARKER = '检查 .fnmap 文件保护...';
const FNMAP_STOP_HOOK_MARKER = 'quality-check.sh';

// PreToolUse 的内联 node 命令 - 禁止 AI 修改 .fnmap 文件
const FNMAP_PROTECT_COMMAND = `node -e "const j=JSON.parse(require('fs').readFileSync(0,'utf8'));const f=j.tool_input?.file_path||'';if(f.endsWith('.fnmap')){console.log(JSON.stringify({hookSpecificOutput:{hookEventName:'PreToolUse',permissionDecision:'deny',permissionDecisionReason:'.fnmap 文件由脚本自动维护，禁止手动修改。请使用 fnmap --changed 命令更新。'}}));}"`;

/** 将 fnmap hooks 安装到项目的 .claude 目录 */
export function installHooks(projectDir: string, detectedTools: DetectedTool[]): void {
  const claudeDir = path.join(projectDir, '.claude');
  const hooksDir = path.join(claudeDir, 'hooks');
  const settingsPath = path.join(claudeDir, 'settings.json');
  const scriptPath = path.join(hooksDir, 'quality-check.sh');

  // 确保目录存在
  fs.mkdirSync(hooksDir, { recursive: true });

  // 1. 生成并写入质量检查脚本
  const script = generateQualityScript(detectedTools);
  fs.writeFileSync(scriptPath, script);

  // 2. 读取已有 settings.json 或创建空对象
  let settings: Record<string, any> = {};
  if (fs.existsSync(settingsPath)) {
    try {
      settings = JSON.parse(fs.readFileSync(settingsPath, 'utf-8'));
    } catch {
      settings = {};
    }
  }

  // 确保 hooks 对象存在
  if (!settings.hooks) settings.hooks = {};

  // 3. 安装/更新 PreToolUse hook（fnmap 文件保护）
  if (!settings.hooks.PreToolUse) settings.hooks.PreToolUse = [];
  // 幂等：移除已有的 fnmap hook
  settings.hooks.PreToolUse = settings.hooks.PreToolUse.filter(
    (h: any) => !h.hooks?.some((hh: any) => hh.statusMessage?.includes('fnmap'))
  );
  settings.hooks.PreToolUse.push({
    matcher: 'Edit|Write',
    hooks: [{
      type: 'command',
      command: FNMAP_PROTECT_COMMAND,
      statusMessage: FNMAP_PRE_HOOK_MARKER
    }]
  });

  // 4. 安装/更新 Stop hook（质量检查）
  if (!settings.hooks.Stop) settings.hooks.Stop = [];
  settings.hooks.Stop = settings.hooks.Stop.filter(
    (h: any) => !h.hooks?.some((hh: any) => hh.command?.includes(FNMAP_STOP_HOOK_MARKER))
  );
  settings.hooks.Stop.push({
    matcher: '',
    hooks: [{
      type: 'command',
      command: 'bash .claude/hooks/quality-check.sh',
      timeout: 120,
      statusMessage: '代码质量检查中...'
    }]
  });

  // 5. 写入 settings.json
  fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2));
}

/** 交互式提问工具 */
function askQuestion(rl: readline.Interface, question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer.trim());
    });
  });
}

/** 交互式 hooks 安装流程 */
export async function executeHooksSetup(projectDir: string, rl?: readline.Interface): Promise<void> {
  const ownRl = !rl;
  if (!rl) {
    rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  }

  try {
    console.log(`\n${COLORS.bold}fnmap - Claude Code Hooks Setup${COLORS.reset}`);
    console.log('='.repeat(50));
    console.log('Detecting project tools...\n');

    const tools = detectTools(projectDir);

    for (const tool of tools) {
      if (tool.detected) {
        console.log(`  ${COLORS.green}✓${COLORS.reset} ${tool.name} (${tool.source})`);
      } else {
        console.log(`  ${COLORS.gray}✗ ${tool.name} (not found)${COLORS.reset}`);
      }
    }

    const enabledTools = tools.filter(t => t.detected);

    console.log(`\nHooks to install:`);
    console.log(`  1. ${COLORS.bold}[protect]${COLORS.reset}  Block AI from editing .fnmap files (PreToolUse)`);
    console.log(`  2. ${COLORS.bold}[fnmap]${COLORS.reset}    Auto-update fnmap index on stop (Stop)`);

    let idx = 3;
    for (const tool of enabledTools) {
      const levelTag = tool.level === 'block' ? 'block on errors' : 'warn on issues';
      console.log(`  ${idx}. ${COLORS.bold}[${tool.name}]${COLORS.reset}${' '.repeat(Math.max(1, 10 - tool.name.length))}${tool.name} check - ${levelTag} (Stop)`);
      idx++;
    }

    const answer = await askQuestion(rl, `\nInstall these hooks to .claude/settings.json? (Y/n): `);
    if (answer.toLowerCase() === 'n') {
      console.log('Skipped hooks installation.');
      return;
    }

    installHooks(projectDir, enabledTools);

    console.log(`\n${COLORS.green}✓${COLORS.reset} Created .claude/hooks/quality-check.sh`);
    console.log(`${COLORS.green}✓${COLORS.reset} Updated .claude/settings.json`);
    console.log(`${COLORS.green}✓${COLORS.reset} Hooks installed! Restart Claude Code session to activate.`);
  } finally {
    if (ownRl && rl) rl.close();
  }
}

/** 检测项目中安装的工具 */
export function detectTools(projectDir: string): DetectedTool[] {
  const pkg = readPkg(projectDir);
  const deps = getDeps(pkg);

  return TOOL_RULES.map(rule => {
    const foundDep = rule.depNames.find(d => deps.has(d));
    if (foundDep) {
      const src = depSource(pkg, foundDep);
      return { name: rule.name, detected: true, source: src || 'dependencies', level: rule.level };
    }
    const configFile = findConfigFile(projectDir, rule.configPatterns);
    if (configFile) {
      return { name: rule.name, detected: true, source: configFile, level: rule.level };
    }
    return { name: rule.name, detected: false, source: '', level: rule.level };
  });
}
